### ISSUE TITLE
Scenes apply their internal actions using bco system permissions

### ISSUE THREAD

**Issue by pLeminoq** [openbase/bco.dal#101]
I can think of two possible solutions to this problem:

* The scene should have access to the permissions used to activate it and use these to perform its internal actions
* Permissions for a scene could be computed depending on the permissions needed to trigger its internal actions

I think the first solution is preferable since it allows to trigger scenes and only apply actions which are permitted.

**Comment by DivineThreepwood** [comment]
Has already been implemented.
