### ISSUE TITLE
bco-validate should display registry inconsistencies.

### ISSUE THREAD

**Issue by DivineThreepwood** [openbase/bco.dal#105]
The bco-validate command should display registries as "INCONSISTENT" if it is the case.
Currently there state is printed as "OK"

**Comment by pLeminoq** [comment]
Implemented through commits:

* openbase/jul@ab34f69fca0a279e755926b93e506c939e24a2bf
* openbase/bco.registry@8726831d490e55320f8a1fd79dd218ae95b0e2bf
* openbase/bco.manager@60b8d0de0aa2ec8469b45231632538ca8d41c7b3
