### ISSUE TITLE
Improve usage of action pipeline

### ISSUE THREAD

**Issue by pLeminoq** [openbase/bco.dal#110]
I think the action pipeline has to be improved to make sure that the responsible action is always set.
For example this is currently not done for restoring snapshots.
And when an agent performs an action is the activation of him responsible?.

This feature is not 100% required for the Google assistant but would improve his response for questions of responsibility.

**Comment by DivineThreepwood** [comment]
Anything still open here? Otherwise close.

**Comment by DivineThreepwood** [comment]
Has been addressed within the last 3 month, responsible action is now always set for any action.
If not explicitly declared, a warning is printed and the responsible action auto generated.
