### ISSUE TITLE
Implement bco session key recovery

### ISSUE THREAD

**Issue by DivineThreepwood** [openbase/bco.dal#122]
The session manager on remote applications should request a new session key in case the controller instance was restarted. Since the remote call exception stack is fully recovered this feature can be implemented by just handling the authentication exceptions.

Please use ```ExceptionProcessor.getInitialCause(final Throwable throwable)``` to detect the initial cause of a RPC exception.

**Comment by pLeminoq** [comment]
Has been implemented with the ReLoginFuture.
