### ISSUE TITLE
UnitGroupRemote does not support applyActionAuthenticated

### ISSUE THREAD

**Issue by pLeminoq** [openbase/bco.dal#125]
This issue currently blocks the cloud connector from dealing with groups correctly. Because it initializes requests with tokens the default apply action method cannot be used.
This should be implemented on remote side as the normal apply action method. One issue with this is that the service remote manager would need to decrypt the action description to select the matching service remote. Therefore only the default session manager could be used.
Furthermore it should be checked if this issue also exists for location remotes.

**Comment by DivineThreepwood** [comment]
this issue has been fixed, right?

**Comment by pLeminoq** [comment]
Issue is fixed. Is now implemented on controller side.
