### ISSUE TITLE
how to restore snapshot authenticated after removing the ActionFuture type?

### ISSUE THREAD

**Issue by DivineThreepwood** [openbase/bco.dal#132]
ServiceRemoteManager:359
<pre>
for (Future<ActionDescription> ActionDescription : input) {
                                    //todo release tamino: how to deal with it after removing the ActionFuture?
//                                    AuthenticationClientHandler.handleServiceServerResponse(authenticationBaseData.getSessionKey(), initializedTicket, ActionDescription.get().getTicketAuthenticatorWrapper());
                                }
</pre>

**Comment by pLeminoq** [comment]
The ServiceRemoteManager should call applyActionAuthenticated on the unit remotes and use the ticket within the returned AuthenticatedValue.
Has been implemented in commit cd87af202213d40f3a210ca7f2ea2cc4f3b67e1d.
