### ISSUE TITLE
pre-advertizing of unit states

### ISSUE THREAD

**Issue by DivineThreepwood** [openbase/bco.dal#2]
It would be nice to get notified about new requested unit states. Currently only the actual unit states are request able and notifier ed. 

* This would be good for UI Feedback
* For optimizing the power synchronizer to handle target delays.

**Comment by pLeminoq** [comment]
Has been implemented on the feature-virtual-unit branch and the PowerStateSynchronizer has also been updated accordingly.
In addition to requested states, the last state is now also notified.

**Comment by DivineThreepwood** [comment]
was been released.
