### ISSUE TITLE
Reactivate and test DimmableLightRemoteTest in DAL

### ISSUE THREAD

**Issue by DivineThreepwood** [openbase/bco.dal#30]
This test is currently (maybe because of #17) disabled.
Because the issue is know fixed the test should be reimplemented and tested

**Comment by pLeminoq** [comment]
The mockRegistry registered a dimmer instead of a dimmableLight which was used for the test.
Fixed through commits:

- openbase/bco.registry c808e0b6a370f2d88536beb8db2631f97b1cfae1
- openbase/bco.manager 222f823615c7e4a53f07511b7296d09a3ab7a90e
