### ISSUE TITLE
Scene Editor cannot load scenes with disabled units

### ISSUE THREAD

**Issue by pLeminoq** [openbase/bco.dal#32]
<pre>
17:29:45.169 [AWT-EventQueue-0] INFO  o.o.b.d.v.u.GenericUnitCollectionPanel Add Dimmer with POWER_STATE_SERVICE value: OFF
to unit panel.
17:29:45.178 [AWT-EventQueue-0] INFO  o.o.b.d.v.u.GenericUnitCollectionPanel Creating unit panel with command to set a value!
17:29:45.178 [AWT-EventQueue-0] INFO  o.o.b.d.v.u.GenericUnitPanel Setup unit remote: acfc8c85-b647-4666-bc00-a83386f5db82
17:29:45.210 [AWT-EventQueue-0] ERROR o.o.b.d.v.u.GenericUnitPanel Skip Service[INTENSITY_STATE_SERVICE] activation because no related service panel registered!
17:29:45.210 [AWT-EventQueue-0] WARN  o.o.b.d.r.u.DimmerRemote Waiting for data of an disabled unit should be avoided! Probably this method will block forever!
17:29:45.214 [AWT-EventQueue-0] WARN  o.o.b.m.s.v.SceneCreationPanel ═╦═⚀ Could not notify observers!
17:29:45.214 [pool-2-thread-41] ERROR o.o.b.d.r.u.DimmerRemote ═╦═⚀ Sync aborted of /home/bath/dimmer/dimmer/
17:29:45.214 [pool-2-thread-41] ERROR o.o.b.d.r.u.DimmerRemote  ╚════⚀ Remote service is not active!
17:29:45.214 [pool-2-thread-41] ERROR o.o.b.d.r.u.DimmerRemote =====================================
17:29:45.215 [AWT-EventQueue-0] WARN  o.o.b.m.s.v.SceneCreationPanel  ╚══╦═⚄ Could not notify Data[[action_authority {  authority: USER}action_priority {  priority: NORMAL}unit_id: "acfc8c85-b647-4666-bc00-a83386f5db82"service_type: POWER_STATE_SERVICEservice_attribute: "{\"value\": \"OFF\"}"service_attribute_type: "rst.domotic.state.PowerStateType$PowerState", action_authority {  authority: USER}action_priority {  priority: NORMAL}unit_id: "efa33b37-8809-4483-beed-480fd9b50446"service_type: POWER_STATE_SERVICEservice_attribute: "{\"value\": \"OFF\"}"service_attribute_type: "rst.domotic.state.PowerStateType$PowerState", action_authority {  authority: USER}action_priority {  priority: NORMAL}unit_id: "31b4fd8f-6355-49c2-90bc-039e92d602f0"service_type: POWER_STATE_SERVICEservice_attribute: "{\"value\": \"OFF\"}"service_attribute_type: "rst.domotic.state.PowerStateType$PowerState", action_authority {  authority: USER}action_priority {  priority: NORMAL}unit_id: "0529ab14-ea69-4c54-9e7a-2288f7b0a5ec"service_type: POWER_STATE_SERVICEservice_attribute: "{\"value\": \"OFF\"}"service_attribute_type: "rst.domotic.state.PowerStateType$PowerState", action_authority {  authority: USER}action_priority {  priority: NORMAL}unit_id: "b71892c9-cb68-4f6c-9e1b-8837d3c28e1e"service_type: POWER_STATE_SERVICEservice_attribute: "{\"value\": \"OFF\"}"service_attribute_type: "rst.domotic.state.PowerStateType$PowerState", action_authority {  authority: USER}action_priority {  priority: NORMAL}unit_id: "afa64bbf-7e9c-40fe-a6a7-a368c8a01eaf"service_type: POWER_STATE_SERVICEservice_attribute: "{\"value\": \"OFF\"}"service_attribute_type: "rst.domotic.state.PowerStateType$PowerState", action_authority {  authority: USER}action_priority {  priority: NORMAL}unit_id: "020cf35d-e6a9-4af8-9f3c-16184dff8d36"service_type: POWER_STATE_SERVICEservice_attribute: "{\"value\": \"OFF\"}"service_attribute_type: "rst.domotic.state.PowerStateType$PowerState"]] to all observer!
17:29:45.215 [AWT-EventQueue-0] WARN  o.o.b.m.s.v.SceneCreationPanel     ╚════⚀ CancellationException
17:29:45.215 [AWT-EventQueue-0] WARN  o.o.b.m.s.v.SceneCreationPanel =====================================

</pre>

**Comment by pLeminoq** [comment]
I just tested this and it seems to be fixed by now. Services of disabled units will just not be loaded.

**Comment by DivineThreepwood** [comment]
Scene Editor not supported anymore. Use new registry editor for scene configuration purpose.
