### ISSUE TITLE
Updated Timestamps results disables the observable filter function

### ISSUE THREAD

**Issue by DivineThreepwood** [openbase/bco.dal#34]
Since we fixed the timestamp update, the data load is changed in every data update because of the including timestamp field.

**Comment by pLeminoq** [comment]
Should be fixed by commits:

- openbase/jul@fce5a35b9cd97f0f8dc69975b29273475e3c3e8e
- openbase/jul@e4fa4e5161fd3023857622fd03547304dbf5ec02
