### ISSUE TITLE
Integrate reed contacts in kitchen handles

### ISSUE THREAD

**Issue by DivineThreepwood** [openbase/bco.dal#36]
The kitchen handles of the csra are not jet integrated in bco.

* The device class should be extended by a reed switch unit.
* Verify that the inkg lib is handling the reed switch unit protocol like expected.
* Implement java usage example

**Comment by pLeminoq** [comment]
DeviceClass is extended and the inkg lib updated. An example still has to be implemented.

**Comment by DivineThreepwood** [comment]
Example has been implemented:
* [Complete Code Example](https://github.com/openbase/bco.dal/blob/master/example/src/main/java/org/openbase/bco/dal/example/HowToObserveLocationSpecificReedContactsViaDAL.java)
