### ISSUE TITLE
Feature - DAL Unit Simulator

### ISSUE THREAD

**Issue by DivineThreepwood** [openbase/bco.dal#38]
* Implement unit and service simulator framework.
* Implement custom and generic simulators.

**Comment by pLeminoq** [comment]
Implemented missing serviceSimulator in commits
*openbase/dal@54369422ff64b552710752c71c230dbd08f2a17c
*openbase/dal@d1ff7cb8229447527b751cb33c89f4fa53bf708e
*openbase/dal@3aa8de779426e98054499f2cbc586498c3aba14b
