### ISSUE TITLE
Get notification of changed serviceType content in observer environment

### ISSUE THREAD

**Issue by agatting** [openbase/bco.dal#4]
Get detailed information of changed values of a remote via serviceTypes.
This permits prefiltering (in e.g. ontology.lib) and an update of changed information of the remotes only (instead of all remote content).

**Comment by DivineThreepwood** [comment]
Service observation is now defined in the `org.openbase.bco.dal.lib.layer.service.ServiceProvider` interface. 

The following methods are now implemented by all unit and service remotes:
*  ```public void addServiceStateObserver(ServiceType serviceType, final Observer observer);```
*  ```public void removeServiceStateObserver(ServiceType serviceType, final Observer observer);```
