### ISSUE TITLE
Introduce services for user

### ISSUE THREAD

**Issue by pLeminoq** [openbase/bco.dal#44]
Currently the user provides methods for its activity state and presence state which are not defined by services.

**Comment by pLeminoq** [comment]
ServiceTypes have been added in rst.

**Comment by pLeminoq** [comment]
Introduced by updating the registry:

* openbase/bco.registry.service-template-db@a0494bbb3bd7400716aba5cb30e26fed90ce82e7
* openbase/bco.registry.unit-template-db@2fcacd31648868dcbf13cfc2470039ee99737e58

and following commits in dal and the manager:

* bb476e363a0c2fb2ff04e8c85a4e06e11a5de2d0
* openbase/bco.manager@405d9e17be44b9e06cf0e15dbe1275107a0c9d0b

**Comment by DivineThreepwood** [comment]
verified
