### ISSUE TITLE
Implement a stack of next state for services

### ISSUE THREAD

**Issue by pLeminoq** [openbase/bco.dal#66]
This includes adding a repeated field of next values for every unit data type.

**Comment by pLeminoq** [comment]
Is this still planned or already done by adding a requested state?

**Comment by pLeminoq** [comment]
This is still needed and should be used to avoid polling during resource scheduling and additionally decentralize the resource allocation so that each unit can do this for itself.

The stack should not be moved added to the data type but kept locally by the controller.

**Comment by DivineThreepwood** [comment]
What exactly do you mean with next state? Is this issue already outdated?

**Comment by DivineThreepwood** [comment]
Outdated since its covered by the actionList which is delivered via each unit data type
