### ISSUE TITLE
ColorType can not be detected.

### ISSUE THREAD

**Issue by DivineThreepwood** [openbase/bco.dal#72]
Some times the color type can not be detected:

<pre>
18:58:40.497 [Thread-1089] INFO  o.o.b.d.l.l.u.ColorableLightController Apply action on ColorableLightController[COLORABLE_LIGHT[Lichtschale]]
18:58:40.497 [Thread-1089] INFO  o.o.b.d.l.l.u.ColorableLightController ================
18:58:40.498 [Thread-1089] ERROR o.o.b.d.l.l.u.ColorableLightController ═╦═⚀ org.openbase.jul.exception.CouldNotPerformException: Could not invoke Method[Class applyAction(ActionDescription)]!
18:58:40.498 [Thread-1089] ERROR o.o.b.d.l.l.u.ColorableLightController  ╚══╦═⚀ Could not invoke Method[Class applyAction(ActionDescription)]!
18:58:40.498 [Thread-1089] ERROR o.o.b.d.l.l.u.ColorableLightController     ╚══╦═⚀ InvocationTargetException
18:58:40.498 [Thread-1089] ERROR o.o.b.d.l.l.u.ColorableLightController        ╚══╦═⚀ Could not apply action!
18:58:40.498 [Thread-1089] ERROR o.o.b.d.l.l.u.ColorableLightController           ╚══╦═⚀ Could not initialize class org.openbase.bco.dal.lib.action.ActionImpl!
18:58:40.499 [Thread-1089] ERROR o.o.b.d.l.l.u.ColorableLightController              ╚════⚀ Could not detect color type!
18:58:40.499 [Thread-1089] ERROR o.o.b.d.l.l.u.ColorableLightController =====================================
18:58:40.564 [Thread-334] INFO  o.o.b.m.d.b.o.e.OpenHABCommandExecutor receiveUpdate 
Dec 14, 2017 6:58:40 PM rsb.patterns.LocalMethod internalNotify
WARNING: Exception during method invocation in participant: /chillerstrasse/wohnzimmer/colorablelight/lichtschale/ctrl/applyAction/. Exception message: org.openbase.jul.exception.CouldNotPerformException: Could not invoke Method[Class applyAction(ActionDescription)]!
</pre>

We need:
* to check the code parts for potential erros.
* add some more logging to better get feedback whats exactly is going wrong.

Maybe related?

<pre>
18:58:41.443 [pool-1-thread-20] WARN  o.o.b.d.r.a.RemoteAction ═╦═⚀ Execution UNKNOWN!
18:58:41.443 [pool-1-thread-20] WARN  o.o.b.d.r.a.RemoteAction  ╚══╦═⚀ org.openbase.jul.exception.MultiException: Could not execute all tasks!
18:58:41.443 [pool-1-thread-20] WARN  o.o.b.d.r.a.RemoteAction     ╚══╦═⚄ Could not execute all tasks!
18:58:41.530 [pool-1-thread-20] WARN  o.o.b.d.r.a.RemoteAction        ╚══╦═⚀ org.openbase.jul.exception.CouldNotPerformException: Could not call remote Method[applyAction(ActionDescription)] on Scope[/chillerstrasse/wohnzimmer/colorablelight/lichtschale/ctrl/].
18:58:41.530 [pool-1-thread-20] WARN  o.o.b.d.r.a.RemoteAction           ╚══╦═⚀ Could not call remote Method[applyAction(ActionDescription)] on Scope[/chillerstrasse/wohnzimmer/colorablelight/lichtschale/ctrl/].
18:58:41.530 [pool-1-thread-20] WARN  o.o.b.d.r.a.RemoteAction              ╚══╦═⚀ rsb.RSBException: org.openbase.jul.exception.CouldNotPerformException: Could not invoke Method[Class applyAction(ActionDescription)]! Details: Could not invoke Method[Class applyAction(ActionDescription)]!org.openbase.jul.exception.CouldNotPerformException: Could not invoke Method[Class applyAction(ActionDescription)]!   at org.openbase.jul.extension.rsb.com.RPCHelper$1.internalInvoke(RPCHelper.java:98)   at rsb.patterns.LocalMethod.internalNotify(LocalMethod.java:101)        at rsb.eventprocessing.SingleThreadEventReceivingStrategy$DispatchThread.run(SingleThreadEventReceivingStrategy.java:100)Caused by: java.lang.reflect.InvocationTargetException       at sun.reflect.GeneratedMethodAccessor1456.invoke(Unknown Source)       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)        at java.lang.reflect.Method.invoke(Method.java:498)   at org.openbase.jul.extension.rsb.com.RPCHelper$1.internalInvoke(RPCHelper.java:79)     ... 2 moreCaused by: org.openbase.jul.exception.CouldNotPerformException: Could not apply action!       at org.openbase.bco.dal.lib.layer.unit.AbstractUnitController.applyAction(AbstractUnitController.java:452)    ... 6 moreCaused by: org.openbase.jul.exception.InitializationException: Could not initialize class org.openbase.bco.dal.lib.action.ActionImpl! at org.openbase.bco.dal.lib.action.ActionImpl.init(ActionImpl.java:104)       at org.openbase.bco.dal.lib.layer.unit.AbstractUnitController.applyAction(AbstractUnitController.java:449)      ... 6 moreCaused by: org.openbase.jul.exception.VerificationFailedException: Could not detect color type!     at org.openbase.bco.dal.lib.layer.service.provider.ColorStateProviderService.verifyColor(ColorStateProviderService.java:83)     at org.openbase.bco.dal.lib.layer.service.provider.ColorStateProviderService.verifyColorState(ColorStateProviderService.java:74)      at sun.reflect.GeneratedMethodAccessor1432.invoke(Unknown Source)       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)     at java.lang.reflect.Method.invoke(Method.java:498)      at org.openbase.bco.dal.lib.layer.service.Services.verifyServiceState(Services.java:371)        at org.openbase.bco.dal.lib.action.ActionImpl.init(ActionImpl.java:94)  ... 7 more
18:58:41.531 [pool-1-thread-20] WARN  o.o.b.d.r.a.RemoteAction                 ╚════⚀ org.openbase.jul.exception.CouldNotPerformException: Could not invoke Method[Class applyAction(ActionDescription)]! Details: Could not invoke Method[Class applyAction(ActionDescription)]!org.openbase.jul.exception.CouldNotPerformException: Could not invoke Method[Class applyAction(ActionDescription)]!  at org.openbase.jul.extension.rsb.com.RPCHelper$1.internalInvoke(RPCHelper.java:98)  at rsb.patterns.LocalMethod.internalNotify(LocalMethod.java:101) at rsb.eventprocessing.SingleThreadEventReceivingStrategy$DispatchThread.run(SingleThreadEventReceivingStrategy.java:100)Caused by: java.lang.reflect.InvocationTargetException       at sun.reflect.GeneratedMethodAccessor1456.invoke(Unknown Source)       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)        at java.lang.reflect.Method.invoke(Method.java:498)     at org.openbase.jul.extension.rsb.com.RPCHelper$1.internalInvoke(RPCHelper.java:79)   ... 2 moreCaused by: org.openbase.jul.exception.CouldNotPerformException: Could not apply action!       at org.openbase.bco.dal.lib.layer.unit.AbstractUnitController.applyAction(AbstractUnitController.java:452)    ... 6 moreCaused by: org.openbase.jul.exception.InitializationException: Could not initialize class org.openbase.bco.dal.lib.action.ActionImpl! at org.openbase.bco.dal.lib.action.ActionImpl.init(ActionImpl.java:104)       at org.openbase.bco.dal.lib.layer.unit.AbstractUnitController.applyAction(AbstractUnitController.java:449)      ... 6 moreCaused by: org.openbase.jul.exception.VerificationFailedException: Could not detect color type!     at org.openbase.bco.dal.lib.layer.service.provider.ColorStateProviderService.verifyColor(ColorStateProviderService.java:83)     at org.openbase.bco.dal.lib.layer.service.provider.ColorStateProviderService.verifyColorState(ColorStateProviderService.java:74)      at sun.reflect.GeneratedMethodAccessor1432.invoke(Unknown Source)       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)        at java.lang.reflect.Method.invoke(Method.java:498)   at org.openbase.bco.dal.lib.layer.service.Services.verifyServiceState(Services.java:371)        at org.openbase.bco.dal.lib.action.ActionImpl.init(ActionImpl.java:94)  ... 7 more
18:58:41.531 [pool-1-thread-20] WARN  o.o.b.d.r.a.RemoteAction 
</pre>

**Comment by pLeminoq** [comment]
I am not 100% sure but has this not been fixed already?
