### ISSUE TITLE
Sometime the TransactionId is missing.

### ISSUE THREAD

**Issue by DivineThreepwood** [openbase/bco.dal#77]
* Figure out how this is possible, is there still some old jul dependencies used?

<pre>
00:01:01.690 [pool-1-thread-208] WARN  o.o.b.d.r.u.ColorableLightRemote TransactionId has not been set by the controller
</pre>

**Comment by pLeminoq** [comment]
Should this issue still be fixed for old versions or moved to release scrab since with #92 a lot has changed regarding this.
