### ISSUE TITLE
ServiceRemotes do not remove disabled unit remotes

### ISSUE THREAD

**Issue by DivineThreepwood** [openbase/bco.dal#82]
If the system is started and some units are disabled via the registry editor (e.g. the handles) those instances are not removed from the service remotes. If afterwards the bco-validate is executed the feedback is quit clear:
<pre>
=== Check Units ===
15:48:03.017 [pool-1-thread-41] WARN  o.o.b.d.r.s.BrightnessStateServiceRemote Using a disabled ColorableLightRemote[scope:/home/kitchen/colorablelight/506/] in BrightnessStateServiceRemote[serviceType:BRIGHTNESS_STATE_SERVICE] is not recommended and should be avoided!
15:48:03.019 [pool-1-thread-41] WARN  o.o.b.d.r.s.BrightnessStateServiceRemote Using a disabled ColorableLightRemote[scope:/home/kitchen/colorablelight/503/] in BrightnessStateServiceRemote[serviceType:BRIGHTNESS_STATE_SERVICE] is not recommended and should be avoided!
15:48:03.020 [pool-1-thread-41] WARN  o.o.b.d.r.s.BrightnessStateServiceRemote Using a disabled ColorableLightRemote[scope:/home/kitchen/colorablelight/505/] in BrightnessStateServiceRemote[serviceType:BRIGHTNESS_STATE_SERVICE] is not recommended and should be avoided!
15:48:03.020 [pool-1-thread-41] WARN  o.o.b.d.r.s.BrightnessStateServiceRemote Using a disabled ColorableLightRemote[scope:/home/kitchen/colorablelight/507/] in BrightnessStateServiceRemote[serviceType:BRIGHTNESS_STATE_SERVICE] is not recommended and should be avoided!
15:48:03.020 [pool-1-thread-41] WARN  o.o.b.d.r.s.BrightnessStateServiceRemote Using a disabled ColorableLightRemote[scope:/home/kitchen/colorablelight/502/] in BrightnessStateServiceRemote[serviceType:BRIGHTNESS_STATE_SERVICE] is not recommended and should be avoided!
15:48:03.020 [pool-1-thread-41] WARN  o.o.b.d.r.s.PowerStateServiceRemote Using a disabled ColorableLightRemote[scope:/home/kitchen/colorablelight/506/] in PowerStateServiceRemote[serviceType:POWER_STATE_SERVICE] is not recommended and should be avoided!
15:48:03.020 [pool-1-thread-41] WARN  o.o.b.d.r.s.PowerStateServiceRemote Using a disabled ColorableLightRemote[scope:/home/kitchen/colorablelight/503/] in PowerStateServiceRemote[serviceType:POWER_STATE_SERVICE] is not recommended and should be avoided!
15:48:03.020 [pool-1-thread-41] WARN  o.o.b.d.r.s.PowerStateServiceRemote Using a disabled ColorableLightRemote[scope:/home/kitchen/colorablelight/505/] in PowerStateServiceRemote[serviceType:POWER_STATE_SERVICE] is not recommended and should be avoided!
15:48:03.020 [pool-1-thread-41] WARN  o.o.b.d.r.s.PowerStateServiceRemote Using a disabled ColorableLightRemote[scope:/home/kitchen/colorablelight/507/] in PowerStateServiceRemote[serviceType:POWER_STATE_SERVICE] is not recommended and should be avoided!
15:48:03.020 [pool-1-thread-41] WARN  o.o.b.d.r.s.PowerStateServiceRemote Using a disabled ColorableLightRemote[scope:/home/kitchen/colorablelight/502/] in PowerStateServiceRemote[serviceType:POWER_STATE_SERVICE] is not recommended and should be avoided!
15:48:03.020 [pool-1-thread-41] WARN  o.o.b.d.r.s.ColorStateServiceRemote Using a disabled ColorableLightRemote[scope:/home/kitchen/colorablelight/506/] in ColorStateServiceRemote[serviceType:COLOR_STATE_SERVICE] is not recommended and should be avoided!
15:48:03.020 [pool-1-thread-41] WARN  o.o.b.d.r.s.ColorStateServiceRemote Using a disabled ColorableLightRemote[scope:/home/kitchen/colorablelight/503/] in ColorStateServiceRemote[serviceType:COLOR_STATE_SERVICE] is not recommended and should be avoided!
15:48:03.020 [pool-1-thread-41] WARN  o.o.b.d.r.s.ColorStateServiceRemote Using a disabled ColorableLightRemote[scope:/home/kitchen/colorablelight/505/] in ColorStateServiceRemote[serviceType:COLOR_STATE_SERVICE] is not recommended and should be avoided!
15:48:03.020 [pool-1-thread-41] WARN  o.o.b.d.r.s.ColorStateServiceRemote Using a disabled ColorableLightRemote[scope:/home/kitchen/colorablelight/507/] in ColorStateServiceRemote[serviceType:COLOR_STATE_SERVICE] is not recommended and should be avoided!
15:48:03.020 [pool-1-thread-41] WARN  o.o.b.d.r.s.ColorStateServiceRemote Using a disabled ColorableLightRemote[scope:/home/kitchen/colorablelight/502/] in ColorStateServiceRemote[serviceType:COLOR_STATE_SERVICE] is not recommended and should be avoided!
             Unit Pool  OK          

       Synchronization  TIMEOUT     [UnitGroupRemote[scope:/home/kitchen/unitgroup/handle_group/]]
</pre>

As well the UnitGroupRemote is not handling the removal but this is eventually just a result of this reported service remote bug.

**Comment by pLeminoq** [comment]
Since commit 6e70bf3888ae4c75e8ae324e975ec62862c45bfc this issue is resolved but it only fixes that disabled units will not be added at the start and not when the enabling state of a unit changes later.
Commit 58d13ed890f4da19ed02a73eadd22272d87b25dc introduces that service remotes are able to deal with changing enabling states of units during run time.
