### ISSUE TITLE
Implement authorized methods for restoring and recording snapshot

### ISSUE THREAD

**Issue by pLeminoq** [openbase/bco.dal#91]
These methods currently can only be used with other rights when using the authentication. Similar methods to the authenticated version of registering/updateing/removing in the registry should be added for snapshot handling.

**Comment by pLeminoq** [comment]
After finishing the initial implementation for restoring snapshots some questions came to my mind:

* Shouldn't the snapshot whole ActionDescriptions rather than ServiceStateDescriptions? 
Otherwise parameters for the resource allocation cannot be set by the user and have to be guessed by the controller. Furthermore it makes it difficult to fill in the correct description. For example as currently done in the ServiceRemoteManager the service attribute has to be deserialized first to update the description.
 
* Why is recording snapshots not done locally? 
I think the answer is to get the most recent state. Maybe I am only a little bit confused because the method is implemented in the unit interface. But if it is not used by unit remotes it should be moved to the unit controller interface

**Comment by pLeminoq** [comment]
Recording of snapshots should be done locally.

**Comment by DivineThreepwood** [comment]
@pLeminoq is this issue solved?

**Comment by pLeminoq** [comment]
Overall, I think this issue is solved. Recording snapshots is performed locally and restoring snapshots is performed in an authenticated way.
