### ISSUE TITLE
PowerSynchronizer does not switch on source if target color has been changed. 

### ISSUE THREAD

**Issue by DivineThreepwood** [openbase/bco.dal#94]
If source and target are switched "off" everything works fine for switching the power state to "on" but if the color of the target is changed the target is displayed as "on" but the source does not switch "on".

**Comment by pLeminoq** [comment]
Added in commit openbase/bco.manager@86e36baed3d830c711180fe2906a2a607a1bd8f3. Still needs to be tested in a live system.

**Comment by DivineThreepwood** [comment]
Outdated 1.6 issue
