### ISSUE TITLE
Service Attributes of Scenes are including timestamps and responsible actions which should be avoided

### ISSUE THREAD

**Issue by DivineThreepwood** [openbase/bco.dal#97]
The action of scenes are including timestamps and responsible actions within there service attribute.
Because the timestamp is related to the execution and the related action is always different depending on the executor this entries should not be stored within the service attribute!

**Comment by pLeminoq** [comment]
The ServiceJsonProcessor which is used for the serialization of service attributes filters the timestamp and responsible action per default after commit 557872fec88b4413a0a36ea15eefd3cae5ffab61.
